import { colors } from '../variables';

// const footerHeight = document.getElementById('footer').offsetHeight;
// eslint-disable-next-line no-unused-vars
export const styles = {
  ChatDiv: {
    position: 'fixed',
    top: 0,
    right: -400,
    flexWrap: 'wrap',
    height: '100%',
    backgroundColor: colors.nav,
    width: 400,
    overflowY: 'hidden',
    zIndex: 2,
  },
  chatHeader: {
    display: 'flex',
    width: 400,
    height: 70,
  },
  chatLabel: {
    backgroundColor: colors.body,
    fontSize: 14,
    textTransform: 'uppercase',
    color: 'white',
    width: 350,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  closeChat: {
    display: 'flex',
    width: 50,
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    padding: 2.5,
    backgroundColor: colors.red,
    cursor: 'pointer',
    overflowX: 'hidden',
  },
  chatBody: {
    height: 'calc(100% - 70px)',
    maxHeight: 'calc(100% - 70px)',
    width: '100%',
  },
  streamHeaders: {
    width: 400,
    backgroundColor: colors.orange,
    padding: '5px 5px 0 5px',
    display: 'flex',
    justifyContent: 'start',
    flexWrap: 'wrap',
  },
  streamHead: {
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.nav,
    color: 'black',
    margin: '0 5px 5px 0',
    fontSize: 11,
    padding: '2px 5px 2px 5px',
    borderRadius: 5,
    overflowX: 'hidden',
  },
  streamHeadActive: {
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.body,
    color: 'white',
    margin: '0 5px 5px 0',
    fontSize: 11,
    padding: '2px 5px 2px 5px',
    borderRadius: 5,
    overflowX: 'hidden',
  },
  streamChat: {
    height: 'calc(100% - 31px)',
    maxHeight: 'calc(100% - 31px)',
    width: 400,
    right: 0,
  }
};
